language: ruby
rvm:
- 2.2.0
cache: bundler
script: bundle exec jekyll build
after_success: bundle exec s3_website push
branches:
  only:
    - master
    - production
    - s3-deploy-yaml
    - s3-staging-test
